[phases.setup]
nixPkgs = ["poppler"]

[phases.install]
cmds = ["cd backend && python3 -m pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "cd backend && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT"

